// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.32.0
// source: pkg/apis/proto/source/v1/source.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Source_ReadFn_FullMethodName       = "/source.v1.Source/ReadFn"
	Source_AckFn_FullMethodName        = "/source.v1.Source/AckFn"
	Source_NackFn_FullMethodName       = "/source.v1.Source/NackFn"
	Source_PendingFn_FullMethodName    = "/source.v1.Source/PendingFn"
	Source_PartitionsFn_FullMethodName = "/source.v1.Source/PartitionsFn"
	Source_IsReady_FullMethodName      = "/source.v1.Source/IsReady"
)

// SourceClient is the client API for Source service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourceClient interface {
	// Read returns a stream of datum responses.
	// The size of the returned responses is less than or equal to the num_records specified in each ReadRequest.
	// If the request timeout is reached on the server side, the returned responses will contain all the datum that have been read (which could be an empty list).
	// The server will continue to read and respond to subsequent ReadRequests until the client closes the stream.
	// Once it has sent all the datum, the server will send a ReadResponse with the end of transmission flag set to true.
	ReadFn(ctx context.Context, opts ...grpc.CallOption) (Source_ReadFnClient, error)
	// AckFn acknowledges a stream of datum offsets.
	// When AckFn is called, it implicitly indicates that the datum stream has been processed by the source vertex.
	// The caller (numa) expects the AckFn to be successful, and it does not expect any errors.
	// If there are some irrecoverable errors when the callee (UDSource) is processing the AckFn request,
	// then it is best to crash because there are no other retry mechanisms possible.
	// Clients sends n requests and expects n responses.
	AckFn(ctx context.Context, opts ...grpc.CallOption) (Source_AckFnClient, error)
	// NackFn negatively acknowledges a batch of offsets. Invoked during a critical error in the mono vertex or pipeline.
	// Unlike AckFn its not a streaming rpc because this is only invoked when there is a critical error (error path).
	NackFn(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error)
	// PendingFn returns the number of pending records at the user defined source.
	PendingFn(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PendingResponse, error)
	// PartitionsFn returns the list of partitions for the user defined source.
	PartitionsFn(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PartitionsResponse, error)
	// IsReady is the heartbeat endpoint for user defined source gRPC.
	IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error)
}

type sourceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceClient(cc grpc.ClientConnInterface) SourceClient {
	return &sourceClient{cc}
}

func (c *sourceClient) ReadFn(ctx context.Context, opts ...grpc.CallOption) (Source_ReadFnClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Source_ServiceDesc.Streams[0], Source_ReadFn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sourceReadFnClient{ClientStream: stream}
	return x, nil
}

type Source_ReadFnClient interface {
	Send(*ReadRequest) error
	Recv() (*ReadResponse, error)
	grpc.ClientStream
}

type sourceReadFnClient struct {
	grpc.ClientStream
}

func (x *sourceReadFnClient) Send(m *ReadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sourceReadFnClient) Recv() (*ReadResponse, error) {
	m := new(ReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sourceClient) AckFn(ctx context.Context, opts ...grpc.CallOption) (Source_AckFnClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Source_ServiceDesc.Streams[1], Source_AckFn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sourceAckFnClient{ClientStream: stream}
	return x, nil
}

type Source_AckFnClient interface {
	Send(*AckRequest) error
	Recv() (*AckResponse, error)
	grpc.ClientStream
}

type sourceAckFnClient struct {
	grpc.ClientStream
}

func (x *sourceAckFnClient) Send(m *AckRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sourceAckFnClient) Recv() (*AckResponse, error) {
	m := new(AckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sourceClient) NackFn(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackResponse)
	err := c.cc.Invoke(ctx, Source_NackFn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) PendingFn(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingResponse)
	err := c.cc.Invoke(ctx, Source_PendingFn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) PartitionsFn(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PartitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionsResponse)
	err := c.cc.Invoke(ctx, Source_PartitionsFn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, Source_IsReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServer is the server API for Source service.
// All implementations must embed UnimplementedSourceServer
// for forward compatibility
type SourceServer interface {
	// Read returns a stream of datum responses.
	// The size of the returned responses is less than or equal to the num_records specified in each ReadRequest.
	// If the request timeout is reached on the server side, the returned responses will contain all the datum that have been read (which could be an empty list).
	// The server will continue to read and respond to subsequent ReadRequests until the client closes the stream.
	// Once it has sent all the datum, the server will send a ReadResponse with the end of transmission flag set to true.
	ReadFn(Source_ReadFnServer) error
	// AckFn acknowledges a stream of datum offsets.
	// When AckFn is called, it implicitly indicates that the datum stream has been processed by the source vertex.
	// The caller (numa) expects the AckFn to be successful, and it does not expect any errors.
	// If there are some irrecoverable errors when the callee (UDSource) is processing the AckFn request,
	// then it is best to crash because there are no other retry mechanisms possible.
	// Clients sends n requests and expects n responses.
	AckFn(Source_AckFnServer) error
	// NackFn negatively acknowledges a batch of offsets. Invoked during a critical error in the mono vertex or pipeline.
	// Unlike AckFn its not a streaming rpc because this is only invoked when there is a critical error (error path).
	NackFn(context.Context, *NackRequest) (*NackResponse, error)
	// PendingFn returns the number of pending records at the user defined source.
	PendingFn(context.Context, *emptypb.Empty) (*PendingResponse, error)
	// PartitionsFn returns the list of partitions for the user defined source.
	PartitionsFn(context.Context, *emptypb.Empty) (*PartitionsResponse, error)
	// IsReady is the heartbeat endpoint for user defined source gRPC.
	IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error)
	mustEmbedUnimplementedSourceServer()
}

// UnimplementedSourceServer must be embedded to have forward compatible implementations.
type UnimplementedSourceServer struct {
}

func (UnimplementedSourceServer) ReadFn(Source_ReadFnServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFn not implemented")
}
func (UnimplementedSourceServer) AckFn(Source_AckFnServer) error {
	return status.Errorf(codes.Unimplemented, "method AckFn not implemented")
}
func (UnimplementedSourceServer) NackFn(context.Context, *NackRequest) (*NackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NackFn not implemented")
}
func (UnimplementedSourceServer) PendingFn(context.Context, *emptypb.Empty) (*PendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingFn not implemented")
}
func (UnimplementedSourceServer) PartitionsFn(context.Context, *emptypb.Empty) (*PartitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionsFn not implemented")
}
func (UnimplementedSourceServer) IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}
func (UnimplementedSourceServer) mustEmbedUnimplementedSourceServer() {}

// UnsafeSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServer will
// result in compilation errors.
type UnsafeSourceServer interface {
	mustEmbedUnimplementedSourceServer()
}

func RegisterSourceServer(s grpc.ServiceRegistrar, srv SourceServer) {
	s.RegisterService(&Source_ServiceDesc, srv)
}

func _Source_ReadFn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SourceServer).ReadFn(&sourceReadFnServer{ServerStream: stream})
}

type Source_ReadFnServer interface {
	Send(*ReadResponse) error
	Recv() (*ReadRequest, error)
	grpc.ServerStream
}

type sourceReadFnServer struct {
	grpc.ServerStream
}

func (x *sourceReadFnServer) Send(m *ReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sourceReadFnServer) Recv() (*ReadRequest, error) {
	m := new(ReadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Source_AckFn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SourceServer).AckFn(&sourceAckFnServer{ServerStream: stream})
}

type Source_AckFnServer interface {
	Send(*AckResponse) error
	Recv() (*AckRequest, error)
	grpc.ServerStream
}

type sourceAckFnServer struct {
	grpc.ServerStream
}

func (x *sourceAckFnServer) Send(m *AckResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sourceAckFnServer) Recv() (*AckRequest, error) {
	m := new(AckRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Source_NackFn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).NackFn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_NackFn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).NackFn(ctx, req.(*NackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_PendingFn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).PendingFn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_PendingFn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).PendingFn(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_PartitionsFn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).PartitionsFn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_PartitionsFn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).PartitionsFn(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_IsReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).IsReady(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Source_ServiceDesc is the grpc.ServiceDesc for Source service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Source_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "source.v1.Source",
	HandlerType: (*SourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NackFn",
			Handler:    _Source_NackFn_Handler,
		},
		{
			MethodName: "PendingFn",
			Handler:    _Source_PendingFn_Handler,
		},
		{
			MethodName: "PartitionsFn",
			Handler:    _Source_PartitionsFn_Handler,
		},
		{
			MethodName: "IsReady",
			Handler:    _Source_IsReady_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFn",
			Handler:       _Source_ReadFn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AckFn",
			Handler:       _Source_AckFn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/apis/proto/source/v1/source.proto",
}
