// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: pkg/apis/proto/function/v1/udfunction.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserDefinedFunctionClient is the client API for UserDefinedFunction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserDefinedFunctionClient interface {
	// Applies a function to each datum element
	DoFn(ctx context.Context, in *Datum, opts ...grpc.CallOption) (*DatumList, error)
	// Applies a reduce function to a datum stream
	ReduceFn(ctx context.Context, opts ...grpc.CallOption) (UserDefinedFunction_ReduceFnClient, error)
}

type userDefinedFunctionClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDefinedFunctionClient(cc grpc.ClientConnInterface) UserDefinedFunctionClient {
	return &userDefinedFunctionClient{cc}
}

func (c *userDefinedFunctionClient) DoFn(ctx context.Context, in *Datum, opts ...grpc.CallOption) (*DatumList, error) {
	out := new(DatumList)
	err := c.cc.Invoke(ctx, "/function.v1.UserDefinedFunction/DoFn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDefinedFunctionClient) ReduceFn(ctx context.Context, opts ...grpc.CallOption) (UserDefinedFunction_ReduceFnClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserDefinedFunction_ServiceDesc.Streams[0], "/function.v1.UserDefinedFunction/ReduceFn", opts...)
	if err != nil {
		return nil, err
	}
	x := &userDefinedFunctionReduceFnClient{stream}
	return x, nil
}

type UserDefinedFunction_ReduceFnClient interface {
	Send(*Datum) error
	CloseAndRecv() (*DatumList, error)
	grpc.ClientStream
}

type userDefinedFunctionReduceFnClient struct {
	grpc.ClientStream
}

func (x *userDefinedFunctionReduceFnClient) Send(m *Datum) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userDefinedFunctionReduceFnClient) CloseAndRecv() (*DatumList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DatumList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserDefinedFunctionServer is the server API for UserDefinedFunction service.
// All implementations must embed UnimplementedUserDefinedFunctionServer
// for forward compatibility
type UserDefinedFunctionServer interface {
	// Applies a function to each datum element
	DoFn(context.Context, *Datum) (*DatumList, error)
	// Applies a reduce function to a datum stream
	ReduceFn(UserDefinedFunction_ReduceFnServer) error
	mustEmbedUnimplementedUserDefinedFunctionServer()
}

// UnimplementedUserDefinedFunctionServer must be embedded to have forward compatible implementations.
type UnimplementedUserDefinedFunctionServer struct {
}

func (UnimplementedUserDefinedFunctionServer) DoFn(context.Context, *Datum) (*DatumList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoFn not implemented")
}
func (UnimplementedUserDefinedFunctionServer) ReduceFn(UserDefinedFunction_ReduceFnServer) error {
	return status.Errorf(codes.Unimplemented, "method ReduceFn not implemented")
}
func (UnimplementedUserDefinedFunctionServer) mustEmbedUnimplementedUserDefinedFunctionServer() {}

// UnsafeUserDefinedFunctionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDefinedFunctionServer will
// result in compilation errors.
type UnsafeUserDefinedFunctionServer interface {
	mustEmbedUnimplementedUserDefinedFunctionServer()
}

func RegisterUserDefinedFunctionServer(s grpc.ServiceRegistrar, srv UserDefinedFunctionServer) {
	s.RegisterService(&UserDefinedFunction_ServiceDesc, srv)
}

func _UserDefinedFunction_DoFn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Datum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDefinedFunctionServer).DoFn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/function.v1.UserDefinedFunction/DoFn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDefinedFunctionServer).DoFn(ctx, req.(*Datum))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDefinedFunction_ReduceFn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserDefinedFunctionServer).ReduceFn(&userDefinedFunctionReduceFnServer{stream})
}

type UserDefinedFunction_ReduceFnServer interface {
	SendAndClose(*DatumList) error
	Recv() (*Datum, error)
	grpc.ServerStream
}

type userDefinedFunctionReduceFnServer struct {
	grpc.ServerStream
}

func (x *userDefinedFunctionReduceFnServer) SendAndClose(m *DatumList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userDefinedFunctionReduceFnServer) Recv() (*Datum, error) {
	m := new(Datum)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserDefinedFunction_ServiceDesc is the grpc.ServiceDesc for UserDefinedFunction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDefinedFunction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "function.v1.UserDefinedFunction",
	HandlerType: (*UserDefinedFunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoFn",
			Handler:    _UserDefinedFunction_DoFn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReduceFn",
			Handler:       _UserDefinedFunction_ReduceFn_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/apis/proto/function/v1/udfunction.proto",
}
