####################################################################################################
# base
####################################################################################################
FROM alpine:3.20 AS base
ARG TARGETARCH
RUN apk update && apk upgrade && \
    apk add ca-certificates && \
    apk --no-cache add tzdata

COPY dist/failure-${TARGETARCH} /bin/failure
RUN chmod +x /bin/failure

####################################################################################################
# failure
####################################################################################################
FROM scratch AS failure
COPY --from=base /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=base /bin/failure /bin/failure
ENTRYPOINT [ "/bin/failure" ]