// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/numaproj/numaflow-go/pkg/apis/proto/map/v1 (interfaces: MapClient,Map_MapStreamFnClient)

// Package mapmock is a generated GoMock package.
package mapmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/numaproj/numaflow-go/pkg/apis/proto/map/v1"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockMapClient is a mock of MapClient interface.
type MockMapClient struct {
	ctrl     *gomock.Controller
	recorder *MockMapClientMockRecorder
}

// MockMapClientMockRecorder is the mock recorder for MockMapClient.
type MockMapClientMockRecorder struct {
	mock *MockMapClient
}

// NewMockMapClient creates a new mock instance.
func NewMockMapClient(ctrl *gomock.Controller) *MockMapClient {
	mock := &MockMapClient{ctrl: ctrl}
	mock.recorder = &MockMapClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapClient) EXPECT() *MockMapClientMockRecorder {
	return m.recorder
}

// IsReady mocks base method.
func (m *MockMapClient) IsReady(arg0 context.Context, arg1 *emptypb.Empty, arg2 ...grpc.CallOption) (*v1.ReadyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsReady", varargs...)
	ret0, _ := ret[0].(*v1.ReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReady indicates an expected call of IsReady.
func (mr *MockMapClientMockRecorder) IsReady(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockMapClient)(nil).IsReady), varargs...)
}

// MapFn mocks base method.
func (m *MockMapClient) MapFn(arg0 context.Context, arg1 *v1.MapRequest, arg2 ...grpc.CallOption) (*v1.MapResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MapFn", varargs...)
	ret0, _ := ret[0].(*v1.MapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapFn indicates an expected call of MapFn.
func (mr *MockMapClientMockRecorder) MapFn(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapFn", reflect.TypeOf((*MockMapClient)(nil).MapFn), varargs...)
}

// MapStreamFn mocks base method.
func (m *MockMapClient) MapStreamFn(arg0 context.Context, arg1 ...grpc.CallOption) (v1.Map_MapStreamFnClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MapStreamFn", varargs...)
	ret0, _ := ret[0].(v1.Map_MapStreamFnClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapStreamFn indicates an expected call of MapStreamFn.
func (mr *MockMapClientMockRecorder) MapStreamFn(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapStreamFn", reflect.TypeOf((*MockMapClient)(nil).MapStreamFn), varargs...)
}

// MockMap_MapStreamFnClient is a mock of Map_MapStreamFnClient interface.
type MockMap_MapStreamFnClient struct {
	ctrl     *gomock.Controller
	recorder *MockMap_MapStreamFnClientMockRecorder
}

// MockMap_MapStreamFnClientMockRecorder is the mock recorder for MockMap_MapStreamFnClient.
type MockMap_MapStreamFnClientMockRecorder struct {
	mock *MockMap_MapStreamFnClient
}

// NewMockMap_MapStreamFnClient creates a new mock instance.
func NewMockMap_MapStreamFnClient(ctrl *gomock.Controller) *MockMap_MapStreamFnClient {
	mock := &MockMap_MapStreamFnClient{ctrl: ctrl}
	mock.recorder = &MockMap_MapStreamFnClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMap_MapStreamFnClient) EXPECT() *MockMap_MapStreamFnClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMap_MapStreamFnClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMap_MapStreamFnClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMap_MapStreamFnClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMap_MapStreamFnClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMap_MapStreamFnClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMap_MapStreamFnClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMap_MapStreamFnClient) Recv() (*v1.MapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.MapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMap_MapStreamFnClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMap_MapStreamFnClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMap_MapStreamFnClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMap_MapStreamFnClient) Send(arg0 *v1.MapRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMap_MapStreamFnClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m *MockMap_MapStreamFnClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMap_MapStreamFnClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMap_MapStreamFnClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMap_MapStreamFnClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMap_MapStreamFnClient)(nil).Trailer))
}
