// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.1
// source: pkg/apis/proto/accumulator/v1/accumulator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Accumulator_AccumulateFn_FullMethodName = "/accumulator.v1.Accumulator/AccumulateFn"
	Accumulator_IsReady_FullMethodName      = "/accumulator.v1.Accumulator/IsReady"
)

// AccumulatorClient is the client API for Accumulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccumulatorClient interface {
	// AccumulateFn applies a accumulate function to a request stream.
	AccumulateFn(ctx context.Context, opts ...grpc.CallOption) (Accumulator_AccumulateFnClient, error)
	// IsReady is the heartbeat endpoint for gRPC.
	IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error)
}

type accumulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAccumulatorClient(cc grpc.ClientConnInterface) AccumulatorClient {
	return &accumulatorClient{cc}
}

func (c *accumulatorClient) AccumulateFn(ctx context.Context, opts ...grpc.CallOption) (Accumulator_AccumulateFnClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Accumulator_ServiceDesc.Streams[0], Accumulator_AccumulateFn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &accumulatorAccumulateFnClient{ClientStream: stream}
	return x, nil
}

type Accumulator_AccumulateFnClient interface {
	Send(*AccumulatorRequest) error
	Recv() (*AccumulatorResponse, error)
	grpc.ClientStream
}

type accumulatorAccumulateFnClient struct {
	grpc.ClientStream
}

func (x *accumulatorAccumulateFnClient) Send(m *AccumulatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *accumulatorAccumulateFnClient) Recv() (*AccumulatorResponse, error) {
	m := new(AccumulatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accumulatorClient) IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, Accumulator_IsReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccumulatorServer is the server API for Accumulator service.
// All implementations must embed UnimplementedAccumulatorServer
// for forward compatibility
type AccumulatorServer interface {
	// AccumulateFn applies a accumulate function to a request stream.
	AccumulateFn(Accumulator_AccumulateFnServer) error
	// IsReady is the heartbeat endpoint for gRPC.
	IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error)
	mustEmbedUnimplementedAccumulatorServer()
}

// UnimplementedAccumulatorServer must be embedded to have forward compatible implementations.
type UnimplementedAccumulatorServer struct {
}

func (UnimplementedAccumulatorServer) AccumulateFn(Accumulator_AccumulateFnServer) error {
	return status.Errorf(codes.Unimplemented, "method AccumulateFn not implemented")
}
func (UnimplementedAccumulatorServer) IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}
func (UnimplementedAccumulatorServer) mustEmbedUnimplementedAccumulatorServer() {}

// UnsafeAccumulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccumulatorServer will
// result in compilation errors.
type UnsafeAccumulatorServer interface {
	mustEmbedUnimplementedAccumulatorServer()
}

func RegisterAccumulatorServer(s grpc.ServiceRegistrar, srv AccumulatorServer) {
	s.RegisterService(&Accumulator_ServiceDesc, srv)
}

func _Accumulator_AccumulateFn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccumulatorServer).AccumulateFn(&accumulatorAccumulateFnServer{ServerStream: stream})
}

type Accumulator_AccumulateFnServer interface {
	Send(*AccumulatorResponse) error
	Recv() (*AccumulatorRequest, error)
	grpc.ServerStream
}

type accumulatorAccumulateFnServer struct {
	grpc.ServerStream
}

func (x *accumulatorAccumulateFnServer) Send(m *AccumulatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *accumulatorAccumulateFnServer) Recv() (*AccumulatorRequest, error) {
	m := new(AccumulatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Accumulator_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Accumulator_IsReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).IsReady(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Accumulator_ServiceDesc is the grpc.ServiceDesc for Accumulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Accumulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accumulator.v1.Accumulator",
	HandlerType: (*AccumulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReady",
			Handler:    _Accumulator_IsReady_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AccumulateFn",
			Handler:       _Accumulator_AccumulateFn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/apis/proto/accumulator/v1/accumulator.proto",
}
