//
//Copyright 2022 The Numaproj Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: sideinput.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SideInput_RetrieveSideInput_FullMethodName = "/sideinput.v1.SideInput/RetrieveSideInput"
	SideInput_IsReady_FullMethodName           = "/sideinput.v1.SideInput/IsReady"
)

// SideInputClient is the client API for SideInput service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SideInputClient interface {
	// RetrieveSideInput is the endpoint to retrieve the latest value of a given Side Input.
	RetrieveSideInput(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SideInputResponse, error)
	// IsReady is the health check endpoint to indicate whether the service is ready to be used.
	IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error)
}

type sideInputClient struct {
	cc grpc.ClientConnInterface
}

func NewSideInputClient(cc grpc.ClientConnInterface) SideInputClient {
	return &sideInputClient{cc}
}

func (c *sideInputClient) RetrieveSideInput(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SideInputResponse, error) {
	out := new(SideInputResponse)
	err := c.cc.Invoke(ctx, SideInput_RetrieveSideInput_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sideInputClient) IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error) {
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, SideInput_IsReady_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SideInputServer is the server API for SideInput service.
// All implementations must embed UnimplementedSideInputServer
// for forward compatibility
type SideInputServer interface {
	// RetrieveSideInput is the endpoint to retrieve the latest value of a given Side Input.
	RetrieveSideInput(context.Context, *emptypb.Empty) (*SideInputResponse, error)
	// IsReady is the health check endpoint to indicate whether the service is ready to be used.
	IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error)
	mustEmbedUnimplementedSideInputServer()
}

// UnimplementedSideInputServer must be embedded to have forward compatible implementations.
type UnimplementedSideInputServer struct {
}

func (UnimplementedSideInputServer) RetrieveSideInput(context.Context, *emptypb.Empty) (*SideInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveSideInput not implemented")
}
func (UnimplementedSideInputServer) IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}
func (UnimplementedSideInputServer) mustEmbedUnimplementedSideInputServer() {}

// UnsafeSideInputServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SideInputServer will
// result in compilation errors.
type UnsafeSideInputServer interface {
	mustEmbedUnimplementedSideInputServer()
}

func RegisterSideInputServer(s grpc.ServiceRegistrar, srv SideInputServer) {
	s.RegisterService(&SideInput_ServiceDesc, srv)
}

func _SideInput_RetrieveSideInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SideInputServer).RetrieveSideInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SideInput_RetrieveSideInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SideInputServer).RetrieveSideInput(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SideInput_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SideInputServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SideInput_IsReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SideInputServer).IsReady(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SideInput_ServiceDesc is the grpc.ServiceDesc for SideInput service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SideInput_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sideinput.v1.SideInput",
	HandlerType: (*SideInputServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveSideInput",
			Handler:    _SideInput_RetrieveSideInput_Handler,
		},
		{
			MethodName: "IsReady",
			Handler:    _SideInput_IsReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sideinput.proto",
}
