package main

import (
	"context"
	"encoding/json"
	"log"
	"time"

	"github.com/numaproj/numaflow-go/pkg/mapper"
)

type Data struct {
	Value uint64 `json:"value,omitempty"`
	// only to ensure a desired message size
	Padding []byte `json:"padding,omitempty"`
}

// payload generated by the generator function
// look at newReadMessage function
type payload struct {
	Data      Data
	Createdts int64
}

type ResultPayload struct {
	Value uint64
	Time  string
}

func mapFn(_ context.Context, keys []string, d mapper.Datum) mapper.Messages {
	msg := d.Value()
	var p = payload{}
	results := mapper.MessagesBuilder()

	var err = json.Unmarshal(msg, &p)
	if err != nil {
		return results
	}

	var v = ResultPayload{
		Value: p.Data.Value,
		Time:  time.Unix(0, p.Createdts).Format(time.RFC3339),
	}
	var r, _ = json.Marshal(v)
	return results.Append(mapper.NewMessage(r).WithKeys(keys))
}

func main() {
	err := mapper.NewServer(mapper.MapperFunc(mapFn)).Start(context.Background())
	if err != nil {
		log.Panic("Failed to start map function server: ", err)
	}
}
