// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: pkg/apis/proto/sourcetransformer/v1/transformer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SourceTransformerClient is the client API for SourceTransformer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourceTransformerClient interface {
	// SourceTransformer applies a function to each request element.
	// In addition to map function, SourceTransformer also supports assigning a new event time to datum.
	// SourceTransformer can be used only at source vertex by source data transformer.
	SourceTransformer(ctx context.Context, in *SourceTransformerRequest, opts ...grpc.CallOption) (*SourceTransformerResponse, error)
	// IsReady is the heartbeat endpoint for gRPC.
	IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error)
}

type sourceTransformerClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceTransformerClient(cc grpc.ClientConnInterface) SourceTransformerClient {
	return &sourceTransformerClient{cc}
}

func (c *sourceTransformerClient) SourceTransformer(ctx context.Context, in *SourceTransformerRequest, opts ...grpc.CallOption) (*SourceTransformerResponse, error) {
	out := new(SourceTransformerResponse)
	err := c.cc.Invoke(ctx, "/sourcetransformer.v1.SourceTransformer/SourceTransformer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceTransformerClient) IsReady(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadyResponse, error) {
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, "/sourcetransformer.v1.SourceTransformer/IsReady", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceTransformerServer is the server API for SourceTransformer service.
// All implementations must embed UnimplementedSourceTransformerServer
// for forward compatibility
type SourceTransformerServer interface {
	// SourceTransformer applies a function to each request element.
	// In addition to map function, SourceTransformer also supports assigning a new event time to datum.
	// SourceTransformer can be used only at source vertex by source data transformer.
	SourceTransformer(context.Context, *SourceTransformerRequest) (*SourceTransformerResponse, error)
	// IsReady is the heartbeat endpoint for gRPC.
	IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error)
	mustEmbedUnimplementedSourceTransformerServer()
}

// UnimplementedSourceTransformerServer must be embedded to have forward compatible implementations.
type UnimplementedSourceTransformerServer struct {
}

func (UnimplementedSourceTransformerServer) SourceTransformer(context.Context, *SourceTransformerRequest) (*SourceTransformerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SourceTransformer not implemented")
}
func (UnimplementedSourceTransformerServer) IsReady(context.Context, *emptypb.Empty) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}
func (UnimplementedSourceTransformerServer) mustEmbedUnimplementedSourceTransformerServer() {}

// UnsafeSourceTransformerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceTransformerServer will
// result in compilation errors.
type UnsafeSourceTransformerServer interface {
	mustEmbedUnimplementedSourceTransformerServer()
}

func RegisterSourceTransformerServer(s grpc.ServiceRegistrar, srv SourceTransformerServer) {
	s.RegisterService(&SourceTransformer_ServiceDesc, srv)
}

func _SourceTransformer_SourceTransformer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceTransformerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceTransformerServer).SourceTransformer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sourcetransformer.v1.SourceTransformer/SourceTransformer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceTransformerServer).SourceTransformer(ctx, req.(*SourceTransformerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceTransformer_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceTransformerServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sourcetransformer.v1.SourceTransformer/IsReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceTransformerServer).IsReady(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceTransformer_ServiceDesc is the grpc.ServiceDesc for SourceTransformer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceTransformer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sourcetransformer.v1.SourceTransformer",
	HandlerType: (*SourceTransformerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SourceTransformer",
			Handler:    _SourceTransformer_SourceTransformer_Handler,
		},
		{
			MethodName: "IsReady",
			Handler:    _SourceTransformer_IsReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/proto/sourcetransformer/v1/transformer.proto",
}
