// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/numaproj/numaflow-go/pkg/apis/proto/function/v1 (interfaces: UserDefinedFunctionClient,UserDefinedFunctionServer)

// Package funcmock is a generated GoMock package.
package funcmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/numaproj/numaflow-go/pkg/apis/proto/function/v1"
	grpc "google.golang.org/grpc"
)

// MockUserDefinedFunctionClient is a mock of UserDefinedFunctionClient interface.
type MockUserDefinedFunctionClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserDefinedFunctionClientMockRecorder
}

// MockUserDefinedFunctionClientMockRecorder is the mock recorder for MockUserDefinedFunctionClient.
type MockUserDefinedFunctionClientMockRecorder struct {
	mock *MockUserDefinedFunctionClient
}

// NewMockUserDefinedFunctionClient creates a new mock instance.
func NewMockUserDefinedFunctionClient(ctrl *gomock.Controller) *MockUserDefinedFunctionClient {
	mock := &MockUserDefinedFunctionClient{ctrl: ctrl}
	mock.recorder = &MockUserDefinedFunctionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDefinedFunctionClient) EXPECT() *MockUserDefinedFunctionClientMockRecorder {
	return m.recorder
}

// DoFn mocks base method.
func (m *MockUserDefinedFunctionClient) DoFn(arg0 context.Context, arg1 *v1.Datum, arg2 ...grpc.CallOption) (*v1.DatumList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DoFn", varargs...)
	ret0, _ := ret[0].(*v1.DatumList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoFn indicates an expected call of DoFn.
func (mr *MockUserDefinedFunctionClientMockRecorder) DoFn(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoFn", reflect.TypeOf((*MockUserDefinedFunctionClient)(nil).DoFn), varargs...)
}

// ReduceFn mocks base method.
func (m *MockUserDefinedFunctionClient) ReduceFn(arg0 context.Context, arg1 ...grpc.CallOption) (v1.UserDefinedFunction_ReduceFnClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReduceFn", varargs...)
	ret0, _ := ret[0].(v1.UserDefinedFunction_ReduceFnClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReduceFn indicates an expected call of ReduceFn.
func (mr *MockUserDefinedFunctionClientMockRecorder) ReduceFn(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReduceFn", reflect.TypeOf((*MockUserDefinedFunctionClient)(nil).ReduceFn), varargs...)
}

// MockUserDefinedFunctionServer is a mock of UserDefinedFunctionServer interface.
type MockUserDefinedFunctionServer struct {
	ctrl     *gomock.Controller
	recorder *MockUserDefinedFunctionServerMockRecorder
}

// MockUserDefinedFunctionServerMockRecorder is the mock recorder for MockUserDefinedFunctionServer.
type MockUserDefinedFunctionServerMockRecorder struct {
	mock *MockUserDefinedFunctionServer
}

// NewMockUserDefinedFunctionServer creates a new mock instance.
func NewMockUserDefinedFunctionServer(ctrl *gomock.Controller) *MockUserDefinedFunctionServer {
	mock := &MockUserDefinedFunctionServer{ctrl: ctrl}
	mock.recorder = &MockUserDefinedFunctionServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDefinedFunctionServer) EXPECT() *MockUserDefinedFunctionServerMockRecorder {
	return m.recorder
}

// DoFn mocks base method.
func (m *MockUserDefinedFunctionServer) DoFn(arg0 context.Context, arg1 *v1.Datum) (*v1.DatumList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoFn", arg0, arg1)
	ret0, _ := ret[0].(*v1.DatumList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoFn indicates an expected call of DoFn.
func (mr *MockUserDefinedFunctionServerMockRecorder) DoFn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoFn", reflect.TypeOf((*MockUserDefinedFunctionServer)(nil).DoFn), arg0, arg1)
}

// ReduceFn mocks base method.
func (m *MockUserDefinedFunctionServer) ReduceFn(arg0 v1.UserDefinedFunction_ReduceFnServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReduceFn", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReduceFn indicates an expected call of ReduceFn.
func (mr *MockUserDefinedFunctionServerMockRecorder) ReduceFn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReduceFn", reflect.TypeOf((*MockUserDefinedFunctionServer)(nil).ReduceFn), arg0)
}

// mustEmbedUnimplementedUserDefinedFunctionServer mocks base method.
func (m *MockUserDefinedFunctionServer) mustEmbedUnimplementedUserDefinedFunctionServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedUserDefinedFunctionServer")
}

// mustEmbedUnimplementedUserDefinedFunctionServer indicates an expected call of mustEmbedUnimplementedUserDefinedFunctionServer.
func (mr *MockUserDefinedFunctionServerMockRecorder) mustEmbedUnimplementedUserDefinedFunctionServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedUserDefinedFunctionServer", reflect.TypeOf((*MockUserDefinedFunctionServer)(nil).mustEmbedUnimplementedUserDefinedFunctionServer))
}
