// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/numaproj/numaflow-go/pkg/apis/proto/sideinput/v1 (interfaces: UserDefinedSideInputClient)

// Package sideinputmock is a generated GoMock package.
package sideinputmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/numaproj/numaflow-go/pkg/apis/proto/sideinput/v1"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockUserDefinedSideInputClient is a mock of UserDefinedSideInputClient interface.
type MockUserDefinedSideInputClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserDefinedSideInputClientMockRecorder
}

// MockUserDefinedSideInputClientMockRecorder is the mock recorder for MockUserDefinedSideInputClient.
type MockUserDefinedSideInputClientMockRecorder struct {
	mock *MockUserDefinedSideInputClient
}

// NewMockUserDefinedSideInputClient creates a new mock instance.
func NewMockUserDefinedSideInputClient(ctrl *gomock.Controller) *MockUserDefinedSideInputClient {
	mock := &MockUserDefinedSideInputClient{ctrl: ctrl}
	mock.recorder = &MockUserDefinedSideInputClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDefinedSideInputClient) EXPECT() *MockUserDefinedSideInputClientMockRecorder {
	return m.recorder
}

// IsReady mocks base method.
func (m *MockUserDefinedSideInputClient) IsReady(arg0 context.Context, arg1 *emptypb.Empty, arg2 ...grpc.CallOption) (*v1.ReadyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsReady", varargs...)
	ret0, _ := ret[0].(*v1.ReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReady indicates an expected call of IsReady.
func (mr *MockUserDefinedSideInputClientMockRecorder) IsReady(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockUserDefinedSideInputClient)(nil).IsReady), varargs...)
}

// RetrieveSideInput mocks base method.
func (m *MockUserDefinedSideInputClient) RetrieveSideInput(arg0 context.Context, arg1 *emptypb.Empty, arg2 ...grpc.CallOption) (*v1.SideInputResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RetrieveSideInput", varargs...)
	ret0, _ := ret[0].(*v1.SideInputResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveSideInput indicates an expected call of RetrieveSideInput.
func (mr *MockUserDefinedSideInputClientMockRecorder) RetrieveSideInput(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveSideInput", reflect.TypeOf((*MockUserDefinedSideInputClient)(nil).RetrieveSideInput), varargs...)
}
