// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pkg/apis/proto/sessionreduce/v1/sessionreduce.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WindowType represents a window type.
// REVISIT Do we need this? Can this be passed using metadata?
type SessionReduceRequest_WindowType int32

const (
	SessionReduceRequest_FIXED   SessionReduceRequest_WindowType = 0
	SessionReduceRequest_SLIDING SessionReduceRequest_WindowType = 1
	SessionReduceRequest_SESSION SessionReduceRequest_WindowType = 2
	SessionReduceRequest_GLOBAL  SessionReduceRequest_WindowType = 3
)

// Enum value maps for SessionReduceRequest_WindowType.
var (
	SessionReduceRequest_WindowType_name = map[int32]string{
		0: "FIXED",
		1: "SLIDING",
		2: "SESSION",
		3: "GLOBAL",
	}
	SessionReduceRequest_WindowType_value = map[string]int32{
		"FIXED":   0,
		"SLIDING": 1,
		"SESSION": 2,
		"GLOBAL":  3,
	}
)

func (x SessionReduceRequest_WindowType) Enum() *SessionReduceRequest_WindowType {
	p := new(SessionReduceRequest_WindowType)
	*p = x
	return p
}

func (x SessionReduceRequest_WindowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionReduceRequest_WindowType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_enumTypes[0].Descriptor()
}

func (SessionReduceRequest_WindowType) Type() protoreflect.EnumType {
	return &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_enumTypes[0]
}

func (x SessionReduceRequest_WindowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionReduceRequest_WindowType.Descriptor instead.
func (SessionReduceRequest_WindowType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{1, 0}
}

type SessionReduceRequest_WindowOperation_Event int32

const (
	SessionReduceRequest_WindowOperation_OPEN   SessionReduceRequest_WindowOperation_Event = 0
	SessionReduceRequest_WindowOperation_CLOSE  SessionReduceRequest_WindowOperation_Event = 1
	SessionReduceRequest_WindowOperation_EXPAND SessionReduceRequest_WindowOperation_Event = 2
	SessionReduceRequest_WindowOperation_MERGE  SessionReduceRequest_WindowOperation_Event = 3
	SessionReduceRequest_WindowOperation_APPEND SessionReduceRequest_WindowOperation_Event = 4
)

// Enum value maps for SessionReduceRequest_WindowOperation_Event.
var (
	SessionReduceRequest_WindowOperation_Event_name = map[int32]string{
		0: "OPEN",
		1: "CLOSE",
		2: "EXPAND",
		3: "MERGE",
		4: "APPEND",
	}
	SessionReduceRequest_WindowOperation_Event_value = map[string]int32{
		"OPEN":   0,
		"CLOSE":  1,
		"EXPAND": 2,
		"MERGE":  3,
		"APPEND": 4,
	}
)

func (x SessionReduceRequest_WindowOperation_Event) Enum() *SessionReduceRequest_WindowOperation_Event {
	p := new(SessionReduceRequest_WindowOperation_Event)
	*p = x
	return p
}

func (x SessionReduceRequest_WindowOperation_Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionReduceRequest_WindowOperation_Event) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_enumTypes[1].Descriptor()
}

func (SessionReduceRequest_WindowOperation_Event) Type() protoreflect.EnumType {
	return &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_enumTypes[1]
}

func (x SessionReduceRequest_WindowOperation_Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionReduceRequest_WindowOperation_Event.Descriptor instead.
func (SessionReduceRequest_WindowOperation_Event) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{1, 0, 0}
}

type Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Key   string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Partition) Reset() {
	*x = Partition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{0}
}

func (x *Partition) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Partition) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Partition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// *
// SessionReduceRequest represents a request element.
type SessionReduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload   *SessionReduceRequest_Payload         `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Operation *SessionReduceRequest_WindowOperation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Type      SessionReduceRequest_WindowType       `protobuf:"varint,3,opt,name=type,proto3,enum=sessionreduce.v1.SessionReduceRequest_WindowType" json:"type,omitempty"`
}

func (x *SessionReduceRequest) Reset() {
	*x = SessionReduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReduceRequest) ProtoMessage() {}

func (x *SessionReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReduceRequest.ProtoReflect.Descriptor instead.
func (*SessionReduceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{1}
}

func (x *SessionReduceRequest) GetPayload() *SessionReduceRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionReduceRequest) GetOperation() *SessionReduceRequest_WindowOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *SessionReduceRequest) GetType() SessionReduceRequest_WindowType {
	if x != nil {
		return x.Type
	}
	return SessionReduceRequest_FIXED
}

// *
// SessionReduceResponse represents a response element.
type SessionReduceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*SessionReduceResponse_Result `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	// Partition represents a window partition to which the result belongs.
	Partition   *Partition `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	CombinedKey string     `protobuf:"bytes,3,opt,name=combinedKey,proto3" json:"combinedKey,omitempty"`
	// Cob to indicate that there won't be any more results for this partition.
	// This is used to indicate that the partition is closed so that the downstream
	// can release the resources associated with the partition.
	EventTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
}

func (x *SessionReduceResponse) Reset() {
	*x = SessionReduceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReduceResponse) ProtoMessage() {}

func (x *SessionReduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReduceResponse.ProtoReflect.Descriptor instead.
func (*SessionReduceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{2}
}

func (x *SessionReduceResponse) GetResult() []*SessionReduceResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SessionReduceResponse) GetPartition() *Partition {
	if x != nil {
		return x.Partition
	}
	return nil
}

func (x *SessionReduceResponse) GetCombinedKey() string {
	if x != nil {
		return x.CombinedKey
	}
	return ""
}

func (x *SessionReduceResponse) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

// *
// ReadyResponse is the health check result.
type ReadyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{3}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// WindowOperation represents a window operation.
// it can be one of OPEN, CLOSE, EXPAND, MERGE, APPEND.
type SessionReduceRequest_WindowOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event      SessionReduceRequest_WindowOperation_Event `protobuf:"varint,1,opt,name=event,proto3,enum=sessionreduce.v1.SessionReduceRequest_WindowOperation_Event" json:"event,omitempty"`
	Partitions []*Partition                               `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
}

func (x *SessionReduceRequest_WindowOperation) Reset() {
	*x = SessionReduceRequest_WindowOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReduceRequest_WindowOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReduceRequest_WindowOperation) ProtoMessage() {}

func (x *SessionReduceRequest_WindowOperation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReduceRequest_WindowOperation.ProtoReflect.Descriptor instead.
func (*SessionReduceRequest_WindowOperation) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SessionReduceRequest_WindowOperation) GetEvent() SessionReduceRequest_WindowOperation_Event {
	if x != nil {
		return x.Event
	}
	return SessionReduceRequest_WindowOperation_OPEN
}

func (x *SessionReduceRequest_WindowOperation) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

// Payload represents a payload element.
type SessionReduceRequest_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys      []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Value     []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	EventTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	Watermark *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=watermark,proto3" json:"watermark,omitempty"`
}

func (x *SessionReduceRequest_Payload) Reset() {
	*x = SessionReduceRequest_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReduceRequest_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReduceRequest_Payload) ProtoMessage() {}

func (x *SessionReduceRequest_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReduceRequest_Payload.ProtoReflect.Descriptor instead.
func (*SessionReduceRequest_Payload) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SessionReduceRequest_Payload) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SessionReduceRequest_Payload) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SessionReduceRequest_Payload) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *SessionReduceRequest_Payload) GetWatermark() *timestamppb.Timestamp {
	if x != nil {
		return x.Watermark
	}
	return nil
}

// Result represents a result element. It contains the result of the reduce function.
type SessionReduceResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys  []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Value []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Tags  []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *SessionReduceResponse_Result) Reset() {
	*x = SessionReduceResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReduceResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReduceResponse_Result) ProtoMessage() {}

func (x *SessionReduceResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReduceResponse_Result.ProtoReflect.Descriptor instead.
func (*SessionReduceResponse_Result) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SessionReduceResponse_Result) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SessionReduceResponse_Result) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SessionReduceResponse_Result) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto protoreflect.FileDescriptor

var file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDesc = []byte{
	0x0a, 0x33, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0xcd, 0x05, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x54, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x1a, 0xe3, 0x01, 0x0a, 0x0f, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3f, 0x0a, 0x05, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x58, 0x50, 0x41, 0x4e,
	0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x50, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x04, 0x1a, 0xa8, 0x01, 0x0a, 0x07, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x39, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x77,
	0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x77, 0x61, 0x74, 0x65,
	0x72, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x3d, 0x0a, 0x0a, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x49, 0x58, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x4c, 0x49, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4c, 0x4f, 0x42,
	0x41, 0x4c, 0x10, 0x03, 0x22, 0xbf, 0x02, 0x0a, 0x15, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64,
	0x4b, 0x65, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x46,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x25, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x32, 0xbb, 0x01,
	0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x12,
	0x66, 0x0a, 0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x46, 0x6e, 0x12, 0x26, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x75, 0x6d, 0x61, 0x70, 0x72,
	0x6f, 0x6a, 0x2f, 0x6e, 0x75, 0x6d, 0x61, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x67, 0x6f, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescOnce sync.Once
	file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescData = file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDesc
)

func file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescGZIP() []byte {
	file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescOnce.Do(func() {
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescData)
	})
	return file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDescData
}

var file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_goTypes = []interface{}{
	(SessionReduceRequest_WindowType)(0),            // 0: sessionreduce.v1.SessionReduceRequest.WindowType
	(SessionReduceRequest_WindowOperation_Event)(0), // 1: sessionreduce.v1.SessionReduceRequest.WindowOperation.Event
	(*Partition)(nil),                               // 2: sessionreduce.v1.Partition
	(*SessionReduceRequest)(nil),                    // 3: sessionreduce.v1.SessionReduceRequest
	(*SessionReduceResponse)(nil),                   // 4: sessionreduce.v1.SessionReduceResponse
	(*ReadyResponse)(nil),                           // 5: sessionreduce.v1.ReadyResponse
	(*SessionReduceRequest_WindowOperation)(nil),    // 6: sessionreduce.v1.SessionReduceRequest.WindowOperation
	(*SessionReduceRequest_Payload)(nil),            // 7: sessionreduce.v1.SessionReduceRequest.Payload
	(*SessionReduceResponse_Result)(nil),            // 8: sessionreduce.v1.SessionReduceResponse.Result
	(*timestamppb.Timestamp)(nil),                   // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                           // 10: google.protobuf.Empty
}
var file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_depIdxs = []int32{
	9,  // 0: sessionreduce.v1.Partition.start:type_name -> google.protobuf.Timestamp
	9,  // 1: sessionreduce.v1.Partition.end:type_name -> google.protobuf.Timestamp
	7,  // 2: sessionreduce.v1.SessionReduceRequest.payload:type_name -> sessionreduce.v1.SessionReduceRequest.Payload
	6,  // 3: sessionreduce.v1.SessionReduceRequest.operation:type_name -> sessionreduce.v1.SessionReduceRequest.WindowOperation
	0,  // 4: sessionreduce.v1.SessionReduceRequest.type:type_name -> sessionreduce.v1.SessionReduceRequest.WindowType
	8,  // 5: sessionreduce.v1.SessionReduceResponse.result:type_name -> sessionreduce.v1.SessionReduceResponse.Result
	2,  // 6: sessionreduce.v1.SessionReduceResponse.partition:type_name -> sessionreduce.v1.Partition
	9,  // 7: sessionreduce.v1.SessionReduceResponse.event_time:type_name -> google.protobuf.Timestamp
	1,  // 8: sessionreduce.v1.SessionReduceRequest.WindowOperation.event:type_name -> sessionreduce.v1.SessionReduceRequest.WindowOperation.Event
	2,  // 9: sessionreduce.v1.SessionReduceRequest.WindowOperation.partitions:type_name -> sessionreduce.v1.Partition
	9,  // 10: sessionreduce.v1.SessionReduceRequest.Payload.event_time:type_name -> google.protobuf.Timestamp
	9,  // 11: sessionreduce.v1.SessionReduceRequest.Payload.watermark:type_name -> google.protobuf.Timestamp
	3,  // 12: sessionreduce.v1.SessionReduce.SessionReduceFn:input_type -> sessionreduce.v1.SessionReduceRequest
	10, // 13: sessionreduce.v1.SessionReduce.IsReady:input_type -> google.protobuf.Empty
	4,  // 14: sessionreduce.v1.SessionReduce.SessionReduceFn:output_type -> sessionreduce.v1.SessionReduceResponse
	5,  // 15: sessionreduce.v1.SessionReduce.IsReady:output_type -> sessionreduce.v1.ReadyResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_init() }
func file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_init() {
	if File_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReduceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReduceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReduceRequest_WindowOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReduceRequest_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReduceResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_goTypes,
		DependencyIndexes: file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_depIdxs,
		EnumInfos:         file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_enumTypes,
		MessageInfos:      file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_msgTypes,
	}.Build()
	File_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto = out.File
	file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_rawDesc = nil
	file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_goTypes = nil
	file_pkg_apis_proto_sessionreduce_v1_sessionreduce_proto_depIdxs = nil
}
