name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Install protoc
      run: |
        set -eux -o pipefail
        PROTOC_VERSION=3.19.4
        PROTOC_ZIP=protoc-$PROTOC_VERSION-linux-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP
        sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
        sudo chmod +x /usr/local/bin/protoc
        sudo find /usr/local/include -type f | xargs sudo chmod a+r
        sudo find /usr/local/include -type d | xargs sudo chmod a+rx
        rm -f $PROTOC_ZIP
        ls /usr/local/include/google/protobuf/

    - name: Install mockgen
      run: |
        go install go.uber.org/mock/mockgen@latest

    - name: Test
      run: make all
